
.PHONY: clean regcompile regrun

clean:
	@/usr/bin/sh clean.sh

regcompile:
	@/usr/bin/sh regcompile.setup.tmp && /usr/bin/sh compile.sh

regrun:
	@/usr/bin/sh regrun.setup.tmp && /usr/bin/sh run.sh
